source 'https://github.com/CocoaPods/Specs.git'


target 'TSMessages' do
  pod "TSMessages", :path => "../"
end

target 'Tests' do
  pod "TSMessages", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase', '~> 1.4'
  pod 'Expecta+Snapshots'
end
